services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  smtp4dev:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
