services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '8025:80'
      - '1025:25'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
